apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: my-app-namespace
data:
  APP_NAME: "MyKubernetesApp"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  MAX_CONNECTIONS: "100"
  config-file: |
    [app]
    name = "MyKubernetesApp"
    version = "1.0.0"
    log_level = "info"

    [database]
    max_connections = 100
    timeout = 30
