apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: my-app-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
